# Generated by Django 4.2.1 on 2023-05-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField()),
                ('longtitude', models.CharField()),
                ('height', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField()),
                ('title', models.CharField()),
                ('other_titles', models.CharField()),
                ('connect', models.CharField()),
                ('add_time', models.DateTimeField()),
                ('winter_lvl', models.CharField()),
                ('summer_lvl', models.CharField()),
                ('autumn_lvl', models.CharField()),
                ('spring_lvl', models.CharField()),
                ('status', models.CharField(choices=[('New', 'new'), ('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected')])),
                ('coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0)),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('fam', models.CharField()),
                ('name', models.CharField()),
                ('otc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField()),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.perevaladded')),
            ],
        ),
    ]
